export const SHOW_MORE_FILMS = 'SHOW_MORE_FILMS';
export const ADD_OR_REMOVE_BOOKMARK = 'ADD_OR_REMOVE_BOOKMARK';
export const CHANGE_DISPLAYED_TAB = 'CHANGE_DISPLAYED_TAB';
export const SEARCH_INPUT_TEXT_CHANGE = 'SEARCH_INPUT_TEXT_CHANGE';
export const ADD_OR_REMOVE_TAG_SEARCH = 'ADD_OR_REMOVE_TAG_SEARCH';
export const CLEAR_SEARCH_PARAMS = 'CLEAR_SEARCH_PARAMS';